### PR TITLE
Add functionality to display custom nickname when available.

### PR DESCRIPTION
**Pull request by marcel-valdez**
Added the capability to display custom nicknames in threads and thread lists. If the user has no custom nickname set, then the normal name is used.

Note: The Messenger.GetLastMessage seems to fail, but I am guessing this is because you no longer have 10 messages in your account? @Alex-Rose

### CODE REVIEW

**Comment by marcel-valdez** [comment]
@Alex-Rose can you review/accept this PR?
Thanks.

**Comment by adrientoub** [comment]
Thank you for looking at my issue!
I just tested your branch on my computer and it works nicely!

Would it be possible to make this feature opt-in (or opt-out?) so that nicknames are displayed only if the user wants it?
In my case I would like to disable it whenever I am using a terminal emulator that doesn't support emojis (as some of my nicknames contain emojis).

**Comment by marcel-valdez** [comment]
Done.

**Comment by Alex-Rose** [comment]
@SamBergeron and I are looking at it

Thanks!

**Comment by Alex-Rose** [comment]
Tried to run from your branch and I got the following error : 
`Found error while fetching conversations. TypeError: Cannot read property 'name' of undefined
    at getThreadName (C:\fb\fb-messenger-cli\scripts\messenger.js:14:23)
    at threads.map.map (C:\fb\fb-messenger-cli\scripts\messenger.js:383:18)
    at Array.map (native)
    at Messenger.parseThreadData (C:\fb\fb-messenger-cli\scripts\messenger.js:382:7)
    at Request.request.post [as _callback] (C:\fb\fb-messenger-cli\scripts\messenger.js:423:32)
    at Request.self.callback (C:\fb\fb-messenger-cli\node_modules\request\request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\fb\fb-messenger-cli\node_modules\request\request.js:1067:10)
    at emitOne (events.js:101:20)`

participant looks undefined. That was on first run so setting don't contain useCustomNicknames

**Comment by marcel-valdez** [comment]
I will look into that failure tonight. I'm surprised, since I've been using this branch locally for a while now.
I am using Linux with node 6.2.1 + npm 3.9.3

What versions of windowze, node & npm are you using? (so I can reproduce your scenario)

**Comment by SamBergeron** [comment]
@marcel-valdez  I got the same error with this on linux. I really doubt it's a node bug.

Though you have to be aware, if you look at the last few commits, there's mention of "GraphQl" version or not. Facebook has been rolling out Messenger API changes by batches, so there are currently two different version of calls in the wild. This may be associated with it, as the return parameters for calls to /threadlist_info, may not necessarily return in the same format as the new /api/graphQlBatch, which returns a much bigger hierarchy of things.

We've pushed some recent commits, with that have some specifics for GraphQl code (special-messages) and that react differently for old calls, even though it says there are no merge conflicts, you might want to merge with cda1412e895c2290e69c2ec75094cf22aa68edf6 to make sure this isn't affecting your code.

Otherwise I'll try and debug it over the weekend when I have more free time.

Thanks for the work.

**Comment by marcel-valdez** [comment]
I rebased from master, uninstalled all node_modules and then tried to reproduce your issue, and still could not. :\

**Comment by marcel-valdez** [comment]
By the way... I am an open-source software contribution virgin.
This is my first time contributing for real to an open source software.

Please be gentle. :kissing_heart:

**Comment by SamBergeron** [comment]
Yeah no worries.
We're not the fastest pull request integrators, but we'll get it done as soon as we have time.
I'll recheck it soon. Thanks!

**Comment by SamBergeron** [comment]
Update on this:
I fixed (most) of it. In your branch you accidentally stopped dealing with group messages, and they don't behave the same way as normal conversations "other_user_fbid" is undefined and you have to look at a "participants" array instead. 
I updated your branch to fix this some other things I wanted that were linked to getThreads. (Liked the ability to select the amount of conversations your want to load).

I'll do a final review tomorrow and should commit during the day. Thanks for being patient.

**Comment by SamBergeron** [comment]
Please check out 461d50ec70fed090c8d4aace21f55fffe56254bf on branch nicknames
@marcel-valdez @Alex-Rose 
Changes from this PR have been moved to that branch. I'll close this soon.

**Comment by Alex-Rose** [comment]
@SamBergeron I tried origin/nicknames and looks like it work well. Here's what I observed
* Nicknames are not visible in groups convos (not implemented yet or bug?)
* In the groups view I now only have 3 convos instead of the regular number (hardcoded 10?)

**Comment by SamBergeron** [comment]
@Alex-Rose  Yeah haven't implemented nicknames in groups, 
and for the three group convos, since we consolidated both types of threads into 1 call, it'll fetch all the group convos listed in the first X convos you call (you have 3, I think I have like 4-5).
At this point... I could probably just consolidate both into a single list and drop /groups completely, thoughts?

**Comment by Alex-Rose** [comment]
We should definitely consolidate convos and groups in one view

**Comment by marcel-valdez** [comment]
@Alex-Rose @SamBergeron  Added your commit to the PR

**Comment by marcel-valdez** [comment]
This branch is broken ATM, need to look into some issues (the stacktraces show where the errors are, but I need to look into it).

**Comment by SamBergeron** [comment]
This has been merged with the last PR #95

**Pull request closed without merging**
