### PR TITLE
Adds "Me" to messages sent by user

### LINKED ISSUE #41: Show sender for messages in main menu
When in the main menu, show whether a message was sent by the user or by the friend.

### PR DESCRIPTION
**Pull request by sarangjo**
Fixes #41, adds indication in main menu for sender.

### CODE REVIEW

**Comment by sarangjo** [comment]
This needs fixing for group messages.

**Comment by sarangjo** [comment]
@Alex-Rose This should be ready to merge! Please review and test and let me know if there's anything I need to fix.

**Comment by Alex-Rose** [comment]
I tried your change and the conversation list won't load anymore

**Comment by sarangjo** [comment]
Hmm yeah that started happening to me too, let me fix that.

**Comment by sarangjo** [comment]
@Alex-Rose Sorry that was a dumb error! Should be fixed now.

**Comment by Alex-Rose** [comment]
Just checked out your PR, the colon ':' does not show up if I'm not the sender of that last message. This feature should be made optional via a setting.
Also just a suggestion, the color could be made customizable. On my terminal red is really hard to read. 
Thanks!

**Comment by sarangjo** [comment]
Ah, that's a good idea, I'll add that to the settings so it's customizable!

**Comment by sarangjo** [comment]
@Alex-Rose Fixed the colon issue and added it to the settings!

**Pull request closed without merging**
