### PR TITLE
login: use chromium with --no-sandbox option

### PR DESCRIPTION
**Pull request by gusano**
Fix https://github.com/Alex-Rose/fb-messenger-cli/issues/143

Not sure this is the recommended way from reading https://github.com/Googlechrome/puppeteer/issues/290 but it seems more and more projects do that and it fixed the issue for me on `4.14.12-1-ARCH` and `node v9.3.0`.

### CODE REVIEW

**Comment by SamBergeron** [comment]
I was thinking of putting this behind an option as opposed to forcing it? Thoughts?

**Comment by gusano** [comment]
@SamBergeron definitively :+1: for me for passing it behind an option

**Comment by gusano** [comment]
@SamBergeron am I supposed to do the option myself? (I'm not sure how as I'm not familiar with your app... if you want me to do it I'd gladly accept hints on how to do it)

**Comment by SamBergeron** [comment]
Haha Sorry I'd assumed you were going to do it, some people just like digging into code and figuring stuff out. 
I just merged and added it behind an option.

**Comment by gusano** [comment]
@SamBergeron yeah I usually do that but I have very few available time.. 
Thank you! :jack_o_lantern:

**Pull request merged**
