### PR TITLE
Create interactive.js

### PR DESCRIPTION
**Pull request by piotryordanov**
I just added a `/b` that allows to be back. It's just faster than typing `/back`

### CODE REVIEW

**Comment by SamBergeron** [comment]
I love that you're too lazy to write /back but you took the time to look at the code and make a PR. :+1:

**Comment by piotryordanov** [comment]
;)

I would go further and have it as a keyboard shortcut, but I see you are reading from stdin, and I'm not sure it accepts commands.

**Comment by piotryordanov** [comment]
Was this pushed in the latest version? I upgraded to 1.6.0 and it ain't there :(

**Comment by SamBergeron** [comment]
Not yet it was just on here. I'll push it to npm with some other changes today and let you know

**Pull request merged**
